### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by small-bamboo** [jensengroup/RMSD_PP_TS#1]
dear friend，i follow the guide to install xyz2mol ,but it also gives an error (ModuleNotFoundError: 
qdrise001@ln06 ~/wulei/ybw/RMSD_PP_TS/1> ./rmsd_pp_ts.py 1r.xyz 1p.xyz success.pkl fail.pkl
/bin/sh: submit_xtb_path: command not found
Traceback (most recent call last):
  File "./rmsd_pp_ts.py", line 1005, in <module>
    PATH_FILE, OUTFILE, N_PATH = find_xtb_path(FILE_1, FILE_2)
  File "./rmsd_pp_ts.py", line 823, in find_xtb_path
    output_list = try_xtb_path(reactant_file, product_file, 0.008,  #change initial push to lower
  File "./rmsd_pp_ts.py", line 799, in try_xtb_path
    reactions_completed_boolean = submit_xtb_path_and_test(reactant_file, product_file,
  File "./rmsd_pp_ts.py", line 785, in submit_xtb_path_and_test
    job_ids = submit_xtb_path_calculation(reactant_file, product_file, kpush,
  File "./rmsd_pp_ts.py", line 49, in submit_xtb_path_calculation
    jobid = int(jobid.split()[-1])
IndexError: list index out of range

)
can you give me a video to show how to run  RMSD_PP_TS?

**Comment by orubaba** [comment]
Hi, Small-bamboo, where you able to see off this issue? I am at the same spot right now and don't know what to do. I will appreciate your quick response. thanks.

**Comment by small-bamboo** [comment]
> 

I didn't go on，you can ask the author
